### ISSUE TITLE
Small copy corrections/typos

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EHDP-data#78]
Indicator 2317:
- Jail Incarceration -> Jail incarceration (sentence case)
- "neighbourhoods" -> neighborhoods
---
Indicator 2380:
- "emegency" -> emergency
---
Babesiosis (2218)
- "Babesiosis s a rare" -> "Babesiosis is a rare..."

**Comment by cgettings** [comment]
Closing, but let's open this issue again if we find more typos.
