### ISSUE TITLE
incorrect rankReverse entries in indicators.json

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EHDP-data#82]
Noticing the following indicators that have rankReverse wrong (is 0, should be 1):
- owner-occupied homes
- renter-occupied homes with no maintenance deficiencies
- subway station density
- recent walking
- walking or biking for transportation
- recent biking
- race/ethnicity
- foreign born
- graduated high school
- limited english
- adults with air conditioners
- homes with grab bars in the bathroom (among older adult households)
- adults with a personal doctor
- self-reported health
- regular exterminator service

~~Will continue review and add to this.~~

**Comment by mmontesanonyc** [comment]
Updated! Took a census of everything, and that's what needs to be updated. We shouldn't go live with this color change until these updates are in place, since we're implying a good/bad thing, and we've got population/demographic indicators needing to be corrected.

**Comment by cgettings** [comment]
Ok, so rankReverse actually comes from the report_content table in the database, which means that any indicators not in a neighborhood report get a rankReverse of 0 by default. We might need to add a column to one of the tables.

**Comment by mmontesanonyc** [comment]
Thanks for looking into it! That's interesting. I had assumed that the db's rankReverse was controlling some oldportal map function, too, since there are different color schemes and directionality in there (i thought). But I guess it was just controlling tertile -> 'better/middle/worse' display.

**Comment by cgettings** [comment]
Indicator tool:

![image](https://user-images.githubusercontent.com/12686912/217912514-8ffc8d38-d1e1-4ebc-b508-b012ec4f4a69.png)

**Comment by mmontesanonyc** [comment]
Beautiful, thank you.

**Comment by mmontesanonyc** [comment]
Heya, checking in on this - [some stuff on development still showing red where it should be green](https://nychealth.github.io/EH-dataportal/data-explorer/social-conditions/?id=2325#display=map) - are the updated rankReverse metadata on production? Or just staging so far? I want to flag that when we push the data explorer enhancements that are bundled with measure to measure, rankReverse needs to be correct so we don't have a variety of social indicators with 'warning' color schemes.

**Comment by mmontesanonyc** [comment]
> Heya, checking in on this - [some stuff on development still showing red where it should be green](https://nychealth.github.io/EH-dataportal/data-explorer/social-conditions/?id=2325#display=map) - are the updated rankReverse metadata on production? Or just staging so far? I want to flag that when we push the data explorer enhancements that are bundled with measure to measure, rankReverse needs to be correct so we don't have a variety of social indicators with 'warning' color schemes.

false alarm! things look fine serving up `data_staging`. Just an environment issue.
