### ISSUE TITLE
typo on Indicator 2237 (driving/messaging)

### ISSUE THREAD

**Issue by etorem** [nychealth/EHDP-data#92]
- [x] Driving is misspelled in the indicator description for indicator 2237
- [x] Add link to interactive HVI for indicator 2191 & 2084, at end of description. `<a href="../../key-topics/climatehealth/hvi">See our interactive Heat Vulnerability Index</a>.`

**Comment by mmontesanonyc** [comment]
@cgettings, adding per Cari's note about linking between DE HVI and iHVI.

**Comment by cgettings** [comment]
all good
